---
title: "Defining Decision Objectives for Team Decisions"
author: "H. Gregg Claycamp"
date: '2014-08-21'
categories:
- MCDA
- project teams
- QRM
- uncertainty
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
lastmod: '2021-01-31'
table_of_contents: true
projects: []
slug: defining-the-objectives
subtitle: ''
summary: This post is about the need for teams to define their decision objectives whenever the decision is important for accomplishing the team's goals. These decisions almost invariably have multiple attributes that can be used as criteria for choosing the best among many alternatives or even creating a prioritized list of alternatives or actions.
tags:
- MCDA
- MCDM
- Quality Risk Management
draft: true
authors: []
bibliography: library-2020-02-05.bib
---

## Introduction

This post is about the need for teams to define their decision objectives whenever the decision is important for accomplishing the team's goals. Important decisions almost always have multiple objective and subjective attributes that can serve as criteria for choosing the best among many alternatives. The process of multi-criteria decision making (MCDM, a.k.a., "MCDA") is well suited for finding an objective solution for complex decisions.[^1] Although the first step in MCDM or MCDA processes is to clearly define the overall objective that the decision maker or decision making group wishes to accomplish, it is often a neglected or poorly executed. Here, I discuss signs and symptoms of a weak MCDM process due to inattention to defining a clear objective.

[^1]: MCDM and multi-criteria decision analysis (MCDA) are often used interchangeably.

```{r echo=FALSE}
#blogdown::shortcode('table_of_contents')
```

## Decisions in teams

Important organizational decision making, whether at the board, managerial, or tactical level, is often accomplished by groups of decision makers. (I will refer to these decision making groups as teams whether or not they are either standing or *ad hoc* teams.) Team decisions making is very diverse including, among many, decisions in strategic planning, selecting a leadership candidate, choosing supplier(s), choosing new sites and prioritizing risk management resources. Depending on a team's function, their decisions can be thought of as either strategic or tactical. Although strategic decisions might follow a formalized decision making process including a facilitator or decision coach, tactical decisions, such as "choose a new supplier," likely rely on informal team discussion. In other instances, a tactical team might be charged by a manager with advising management on choosing a new site or even allocating resources for risk and quality manufacturing. Such decisions benefit from, if not *require*, a more formal decision making process such as MCDA.

Whenever a complex decision--having both *objective* and *subjective* inputs--is before a team, each team member is likely to have a different set of preferences for the outcomes based on a personal mental model of the decision problem. Defining an individual mental model of how the objective and subjective inputs factor into a final choice--given uncertainties--is the subject of classical decision analysis. Classical decision analysis is a complex quantitative approach that is difficult to extend to several or many decision makers. On the other hand, the processes of MCDM/MCDA rely on useful concepts from decision analysis, but are also built from a significant body of literature on "what works" in group decision making. The applicability of MCDA to group decision making has fueled a nearly exponential growth in tools and applications since the 1990s.

## More data improves decisions?

It is paradoxical that accessibility lots of data and information has both complicated and, in my opinion, improved decision making. For example, the personal decision to buy a car historically entailed dealer-to-dealer visits, hearing sales pitches, browsing glossy brochures and test drives. The collection of quantitative data (e.g., horsepower, cost and fuel economy) for even a short list of alternatives (cars) took hours of work. The subjective data, such as your impressions of style, interior comfort and resale appeal, might have taken even longer. In contrast, a few keystrokes on a contemporary search engine can lead to hundreds of pages of data and information about buying cars. Although the volumes of information can be daunting, in fact, judicious use of the information reduces uncertainties in decision making, thereby improving decision making.

The volumes and different types of information make multi-criteria decision making challenging enough for a single decision-maker (discussed below). Adding multiple decision makers to the process only amplifies the complexity. As Keeney outlined in multiple publications, the reasons for inherent complexity include [@Keeney2004; @Keeney2012]:

-   Team members view their common decision differently;

-   Even if the team agrees on the alternatives and consequences, the members may assign different chances to events;

-   Consensus or similar shared decision policies mean that team member's perspectives of the decision and evaluation of the alternatives must be incorporated in the overall decision.

Proponents of MCDA argue that many of the challenges in group decision making can be overcome by following a process that has its roots in ProACT-like procedures [@Hammond2002] and value-focused thinking [@Keeney1992].

### Typical Process steps in MCDA or MCDM

Many authors in the trade and peer-review literature have written how-to books on individual decision making. One of the most useful and accessible books is *Smart Choices* [@Hammond2002]. The book is an excellent introduction to decision making with multiple criteria. The authors recommended a "ProACT/URL" process for these difficult decisions as described in the following table.

|                  |                                      |
|------------------|--------------------------------------|
| **Pr**oblem      | Work on the right decision problem   |
| **O**bjective    | Specify your objectives              |
| **A**lternatives | Create Imaginative alternatives      |
| **C**onsequences | Understand the consequences          |
| **T**rade-offs   | Grapple with your trade-offs         |
| Uncertainty      | Clarify your uncertainties           |
| Risk tolerance   | Think hard about your risk tolerance |
| Linked decisions | Consider linked decisions            |

: Table 1. The PrOACT/URL approach to decision making by [@Hammond2002].

More advanced methods include assessing uncertainties, risk tolerance and whether or not the decision is linked with other decisions. Adding these features, the authors called their process, "ProACT/URL."

Detailed discussions and reviews of MCDA are widely available (MCA; Keeney; von Winterfelt; others). For example, a common procedure is:

1.  Identify and clearly define objectives
2.  Identify alternatives for achieving the objectives
3.  Identify the criteria and attributes to be used to compare the alternatives
4.  Analyze the alternatives and uncertainties: ("modeling" the decision)
5.  Make choice or prioritize options
6.  Examine results and establish a follow-up period.

## The *objective* is the reason for the decision

"The achievement of objectives is the sole reason for being interested in any decision." (see [@Keeney1992]; p. 55). Modern organizations have remarkable access to data and knowledge management tools which can be used to inform both strategic and tactical decisions including the allocation of resources to address risk. Although data and knowledge management contribute to reducing uncertainty in decision making, they neither define nor eliminate uncertainties and risks impacting the achievement of a desired objectives. Multi-criteria decision analysis (MCDA) has evolved as a structured way to define decision objectives and combine the various inputs into objectively quantifying the decision.

This simple statement or the gist of the statement occurs over decades of the MCDM and multi-criteria decision analysis (MCDA) literature. Yet I believe that many decision coaches and advisers will report that the first problem in an individual's decision making process is a lack of a clearly-stated objective. Objectives--the *purpose of the decision---*are sometimes not carefully articulated even for critical decisions. The results of MCDM in the absence of a clear objective is often disappointment and frustration with formal decision making exercises.

Keeney ([@Keeney2004]) offers several explanations for this predicament, including:

-   decision makers do not understand their objectives well
-   decision makers are routinely under time pressure to produce tangible results
-   there is a serious lack of structured approaches to promote systematic and deep thinking about objectives.

The team's work is focused around specific tasks typically organized on a strategic objective.

Think about your experience working in groups or teams who are charged with finding solutions to complex problems, such as developing new information or prioritizing among projects in the organization's tactical plan. Did the group discuss and articulate the key problem objectives, or was the objective "handed down" from the "decision owner" in the form of a committee charge or a problem statement? In some instances, the team's decision objective(s) might be well understood and part of both the culture and business process. But the routine decisions are not the ones we are most interested in understanding and improving. The remainder of this blog post focuses on the difficult, multi-criteria and sometimes, multi-objective, decisions that take us hours, weeks and even years to decide. In those "stuck" decisions, a clear articulation of the decision objectives is crucial to achieve a lasting and satisfying consensus. I will refer to Keeney's key points in turn.

## Decision Makers Don't Understand the Objectives Well Enough

Sometimes, weeks or months into a group decision making process, conversation around the objectives will be heard: "that's not what I heard stated in the working group's/team's charge!" Different understandings of the charge among the group create uncertainty around the purpose or the question, "why are we here?" Group or team uncertainty can often feed on itself until the group finds it necessary to request the decision owner to restate her objectives to the working group. In other situations, a group might reach its decision under an assumed shared understanding of the objectives and then present the decision to the owner only to be told that they answered the *wrong question*.

It should come as no surprise that a group of experts who are diverse in their training and experience will hear and perceive stated objectives differently. For nearly a century psychologists, decision scientists and economists have studied the inevitable intrusion of our subjective, perceiving minds into what is optimistically believed to be an objective decision making process (e.g., Kahneman, D., Thinking, Fast and Slow, 2011; Ariely, D., Predictably Irrational. The Hidden Forces that Shape Our Decisions, 2008; Kahneman, D., Slovic, P. ,Tversky, A. Judgment under Uncertainty: Heuristics and Biases, 1982). Our internal processing of decision objectives is so individualized that we have trouble analyzing other perceptions among the the group. After a career's worth of troubleshooting complex decision and scholarship in decision analysis, Ralph Keeney recently recommend that groups not work through objectives and preference together until each member has defined the problem individually (Keeney, R.L. 2013, Foundations for Group Decision Analysis. *Decision Analysis* **10(2)**:103- 120; <http://dx.doi.org/10.1287/deca.2013.0265>)

The fundamental objectives of the decision capture the reason(s) we are deciding choosing among two or more alternatives (--sometimes known as choices; options). The fundamental objectives are no less important to a decision than are clearly stated and testable hypotheses to a high-quality research design. Even decisions in our personal lives have objectives that a perceived differently by individuals. For example, how many ways might an objective, "achieve personal satisfaction in my career," be perceived and defined among even a small number of individuals?

## Pressure to Produce Tangible Results

Objectives can be parsed into "fundamental objectives" and "means-ends objectives." The former captures the goal(s) of the decision while the latter states ways in which the goals might be achieved. For example, the fundamental objective of "reduce highway auto fatalities" could have an underlying means-end objective, "require driver and passenger seat belt use." The seat belt objective is one of many "actionable" objectives that support the achievement of the fundamental objective---"tangible results." Both animal and human drug review processes share some high-level, fundamental objectives about approving only "safe and effective" drugs. Often, the urge to produce "tangible results" for our review organization shifts the focus to defining means-ends objectives: asking an expert group (e.g.), "how do we evaluate information for the decision?" Certainly, it is possible to charge a working group with solving means-ends objectives-focused problem. But, if the group does not articulate the connections among the means-ends objectives with the overarching fundamental objectives, the decision will not likely be as robust as it would be otherwise.

## A Lack of Structured Approaches?

When Keeney wrote the paragraph (above) in 1992, he was correct in noting the lack of structured approaches for thinking critically through multi-criteria decisions. Two decades later, we have witnessed an exponential growth in research and application of multi-criteria decision analysis (MCDA) of which Keeney's "value-focused thinking" is one of the "best practices." There are numerous examples of MCDA from the government and industry health care that translate efficiently to processes accessible to scientists and clinicians. The structured approaches are now available, and all that remains is the will to implement them. The will to implement MCDA will come from the realization that decision making is an acquired skill based on fundamental decision theory and practice. "Better Blog Tools Create a post Manage posts Manage comments Launch blog program to post The Objectives: Making Decisions Matter - Risk and Decisions Blog Page 1 of 2 decision makers" come from practicing the learned skills. (Keeney, RL 2004, Making better decision makers. Decision Analysis 1(4): 193-204).

## References
