---
title: "Making Sense of Covid-19 Death Tallies"
author: "Gregg Claycamp"
date: '2020-12-15'
output:
  md_document:
    df_print: paged
    toc: true
  pdf_document: default
subtitle: How can they be more meaningful to the public?
draft: yes
slug: covid-19-death-count
summary: The media and Covid-19 tracking websites provide us with daily death counts.
  To most viewers, the numbers of deaths in the US is already staggering; however,
  to others the count  is abstract partly because of the misnformation that Covid-19
  is not a significant cause of death. I discuss some of the reasons that everyday
  folk are underwhelmed or unimpressed by the scale of the coronavirus pandemic.
lastmod: '2020-12-18T09:11:55-05:00'
featured: false
image:
  caption: featured-flu
  focal_point: BottomLeft
  preview_only: no
header:
  image: ''
categories:
- COVID-19
- pandemic
---
## Death counts don't tell the whole story   

We have become accustomed to the daily and the cumulative total death counts by country, states and provinces in countries, and counties within states. Death counts are fundamental measurement in outbreaks, epidemics and pandemics. These numbers are communicated widely by politicians, public health managers and the media. Yet, some of the intended audience seem to be unimpressed by the counts in spite of the frequent comparisons to US losses in the great wars and the 1918 flu pandemic. Why is it underwhelming and dismissed as "no worse than deaths from other causes"? Are there other ways of presenting the death data that might help folks understand just how devastating the pandemic is so far? 

Although it is remarkable in itself that pandemic deniers can dismiss daily death totals greater than the loss from the terrorist attacks of September 11, 2001, what might be at the core of the blase reaction is the context and lack of framework for comparisons. For example, do people in a given county, state, or country have any concept of the daily death counts for "all causes?"    


## Starting with the facts    
If the physicians and pathologists use standardized classification criteria to classify a patient's death as from complications of Covid-19 infection, according to the, then at that moment in time, there is undeniably a body and a cause of death.^[Classification of the cause of death is itself a difficult task. For instance, see the  ]  The same situation exists for the case count: once diagnosed, the case is a factual case. (Note: Both of these measures may change with amendments to the diagnostic criteria as the knowledge base for a disease changes for sometimes years after the outbreak.) 


